name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Build_Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_pass }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .  # Root of the repository
          file: ./Dockerfile  # Path to Dockerfile in the root
          push: true
          tags: |
            lidico36/lidor-miriam-final:${{ github.sha }}
